version: '3'
services:
  mongodb-gui:
    build:
      context: .
    ports:
      - $LOCAL_PORT:80
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - DB_COLLECTION=$DB_COLLECTION
